CREATE INDEX users_roles_by_role ON identity.user_roles(role_id,user_id);
CREATE INDEX session_families_by_user ON identity.session_families(user_id,created_at DESC,id);
CREATE INDEX sessions_by_family ON identity.sessions(family_id);
CREATE INDEX sessions_retention ON identity.sessions(refresh_expires_at,id);
CREATE INDEX exams_browse ON catalog.exams(category,created_at DESC,id DESC) WHERE published AND archived_at IS NULL;
CREATE INDEX exams_browse_all ON catalog.exams(created_at DESC,id DESC) WHERE published AND archived_at IS NULL;
CREATE INDEX bank_questions_cursor ON catalog.questions(created_at DESC,id DESC) WHERE archived_at IS NULL;
CREATE INDEX draft_questions_source ON catalog.exam_questions(question_id,exam_id);
CREATE INDEX frozen_questions_page ON catalog.published_questions(version_id,section_id,position,id);
CREATE UNIQUE INDEX one_active_attempt ON assessment.attempts(user_id,exam_id) WHERE status IN ('CREATED','IN_PROGRESS');
CREATE INDEX attempts_limit ON assessment.attempts(user_id,exam_id);
CREATE INDEX attempts_deadline ON assessment.attempts(deadline,id) WHERE status='IN_PROGRESS';
CREATE INDEX attempts_history ON assessment.attempts(user_id,started_at DESC,id DESC);
CREATE INDEX attempts_admin ON assessment.attempts(version_id,started_at DESC,id DESC);
CREATE INDEX leaderboard_order ON assessment.leaderboard_entries(version_id,earned_points DESC,submitted_at,attempt_id) INCLUDE (user_id,completion_sequence);
CREATE INDEX receipts_retention ON platform.idempotency_receipts(accepted_at,actor_id,key);
CREATE INDEX outbox_ready ON platform.outbox(available_at,created_at,event_id) WHERE delivered_at IS NULL AND parked_at IS NULL;
CREATE INDEX outbox_aggregate ON platform.outbox(aggregate_id);
CREATE INDEX inbox_attempt ON platform.inbox(attempt_id);
CREATE INDEX quarantined_attempt ON platform.quarantined_jobs(attempt_id);
CREATE INDEX audit_resource ON platform.audit_logs(resource_id,occurred_at DESC,id DESC);
CREATE INDEX audit_actor ON platform.audit_logs(actor_id,occurred_at DESC,id DESC);
CREATE INDEX audit_retention ON platform.audit_logs(occurred_at,id);
CREATE INDEX rate_limit_expiry ON platform.rate_limit_buckets(expires_at);
CREATE INDEX import_reports_actor ON platform.import_reports(actor_id,created_at DESC,id DESC);
