import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { Pool } from "pg";
import { databaseConfig } from "../../src/config/database.config";
import { loadMigrations, migrate } from "../../src/infrastructure/database/migration-runner";
import { PostgresDatabase } from "../../src/infrastructure/database/transaction/postgres-database";
import { DeadlineSweep } from "../../src/modules/assessment/application/services/deadline-sweep";
import {
  claimDueSql,
  PostgresAttemptRepository,
} from "../../src/modules/assessment/infrastructure/persistence/postgres-attempt.repository";
import { PostgresSubmissionOutbox } from "../../src/modules/assessment/infrastructure/persistence/postgres-submission-outbox";

// These regressions use disposable databases and real restricted logins. They do
// not execute an archived diagnostic writer or require Identity credentials.
const adminUrl = process.env.TEST_DATABASE_ADMIN_URL;
if (!adminUrl) throw new Error("Local test administrator required");
if (new URL(adminUrl).port === "55432") {
  throw new Error("Expiry regression tests must not use the development database");
}
const suffix = randomUUID().replaceAll("-", "").slice(0, 12);
const name = `expiry_fixes_${suffix}`;
const owner = `expiry_fix_ddl_${suffix}`;
const runtimeLogin = `expiry_fix_api_${suffix}`;
const workerLogin = `expiry_fix_worker_${suffix}`;
const password = randomUUID();
const admin = new Pool({ connectionString: adminUrl, max: 1 });
const fixtureUrl = new URL(adminUrl);
fixtureUrl.pathname = `/${name}`;

function loginUrl(login: string): string {
  const url = new URL(fixtureUrl);
  url.username = login;
  url.password = password;
  return url.toString();
}

function config(url: string, max = 2) {
  return databaseConfig({
    NODE_ENV: "test",
    DATABASE_URL: url,
    DB_POOL_MAX: String(max),
    DB_MAX_WAITING: "4",
    DB_ACQUIRE_TIMEOUT_MS: "1000",
    DB_STATEMENT_TIMEOUT_MS: "2000",
    DB_LOCK_TIMEOUT_MS: "500",
    DB_IDLE_TRANSACTION_TIMEOUT_MS: "5000",
    DB_SSL: "false",
  });
}

let fixture: Pool;
let runtimeDb: PostgresDatabase;
let workerDb: PostgresDatabase;
let secondWorkerDb: PostgresDatabase;
let published: { examId: string; versionId: string };
const fixtureErrors: string[] = [];
let migrationUpgradeVerified = false;

function sweep(db: PostgresDatabase, batch: number): DeadlineSweep {
  return new DeadlineSweep(
    new PostgresAttemptRepository(db),
    new PostgresSubmissionOutbox(db),
    db,
    batch,
  );
}

async function insertUser(): Promise<string> {
  const id = randomUUID();
  await fixture.query(
    `
    INSERT INTO identity.users (id, email, password_hash, display_name)
    VALUES
      ($1, $2, 'fixture-not-a-real-password-hash', 'Expiry regression')
    `,
    [id, `${id}@example.test`],
  );
  return id;
}

async function seedAttempt(deadlineOffsetSeconds = -60): Promise<string> {
  const id = randomUUID();
  const userId = await insertUser();
  await fixture.query(
    `
    INSERT INTO assessment.attempts (
      id,
      user_id,
      exam_id,
      version_id,
      status,
      started_at,
      deadline,
      revision
    )
    VALUES (
      $1,
      $2,
      $3,
      $4,
      'IN_PROGRESS',
      clock_timestamp() - interval '2 hours',
      clock_timestamp() + ($5::integer * interval '1 second'),
      1
    )
    `,
    [id, userId, published.examId, published.versionId, deadlineOffsetSeconds],
  );
  return id;
}

async function state(id: string) {
  const row = (
    await fixture.query<{
      status: string;
      revision: number;
      submission_kind: string | null;
      submission_id: string | null;
      submission_event_id: string | null;
      user_id: string;
      expiry_retry_count: number;
      expiry_retry_after: Date | null;
      events: number;
    }>(
      `
      SELECT
        a.status,
        a.revision,
        a.submission_kind,
        a.submission_id,
        a.submission_event_id,
        a.user_id,
        a.expiry_retry_count,
        a.expiry_retry_after,
        (
          SELECT
            count(*)::integer
          FROM
            platform.outbox o
          WHERE
            o.aggregate_id = a.id
        ) AS events
      FROM
        assessment.attempts a
      WHERE
        a.id = $1
      `,
      [id],
    )
  ).rows[0];
  if (!row) throw new Error("Attempt fixture missing");
  return row;
}

async function rejectOutboxFor(ids: readonly string[]): Promise<void> {
  // IDs are generated by this fixture; no request data is interpolated.
  const constants = ids.map((id) => `'${id}'::uuid`).join(", ");
  await fixture.query(`
    CREATE FUNCTION public.expiry_fix_poison() RETURNS trigger
    LANGUAGE plpgsql AS $fn$
    BEGIN
      IF NEW.aggregate_id = ANY (ARRAY[${constants}]) THEN
        RAISE EXCEPTION 'isolated expiry regression poison' USING ERRCODE = 'P0001';
      END IF;
      RETURN NEW;
    END
    $fn$
  `);
  await fixture.query(`
    CREATE TRIGGER expiry_fix_poison
      BEFORE INSERT ON platform.outbox
      FOR EACH ROW EXECUTE FUNCTION public.expiry_fix_poison()
  `);
}

async function clearOutboxFailure(): Promise<void> {
  await fixture.query("DROP TRIGGER IF EXISTS expiry_fix_poison ON platform.outbox");
  await fixture.query("DROP FUNCTION IF EXISTS public.expiry_fix_poison()");
  await fixture.query("DROP TRIGGER IF EXISTS expiry_fix_delay ON platform.outbox");
  await fixture.query("DROP FUNCTION IF EXISTS public.expiry_fix_delay()");
  await fixture.query("DROP TABLE IF EXISTS public.expiry_fix_commit_witness");
}

async function updateAccepted(db: PostgresDatabase, id: string, kind: string | null) {
  return db.query(
    "assessment.write",
    `
    UPDATE assessment.attempts
    SET
      status = CASE WHEN deadline <= clock_timestamp() THEN 'EXPIRED' ELSE 'SUBMITTED' END,
      submitted_at = clock_timestamp(),
      submission_id = gen_random_uuid(),
      submission_event_id = gen_random_uuid(),
      expired = deadline <= clock_timestamp(),
      submission_kind = $2,
      revision = revision + 1
    WHERE
      id = $1
    `,
    [id, kind],
  );
}

beforeAll(async () => {
  await admin.query(`CREATE DATABASE ${name}`);
  await admin.query(await readFile("infra/database/roles.sql", "utf8"));
  await admin.query(`GRANT CREATE ON DATABASE ${name} TO examination_owner`);
  for (const login of [owner, runtimeLogin, workerLogin]) {
    await admin.query(
      `CREATE ROLE ${login} LOGIN ${login === owner ? "NOINHERIT" : "INHERIT"} PASSWORD '${password}'`,
    );
  }
  await admin.query(`GRANT examination_owner TO ${owner}`);
  await admin.query(`GRANT examination_runtime TO ${runtimeLogin}`);
  await admin.query(`GRANT examination_expiry_worker TO ${workerLogin}`);
  const migrations = await loadMigrations("apps/api/src/infrastructure/database/migrations");
  await migrate(config(loginUrl(owner), 1), migrations.slice(0, 11));
  fixture = new Pool({ connectionString: fixtureUrl.toString(), max: 3 });
  fixture.on("error", (error: Error & { code?: string }) => {
    fixtureErrors.push(error.code ?? "unknown");
  });
  runtimeDb = new PostgresDatabase(config(loginUrl(runtimeLogin)));
  workerDb = new PostgresDatabase(config(loginUrl(workerLogin)));
  secondWorkerDb = new PostgresDatabase(config(loginUrl(workerLogin)));
  const publisher = await insertUser();
  published = { examId: randomUUID(), versionId: randomUUID() };
  const publication = await fixture.connect();
  try {
    await publication.query("BEGIN");
    await publication.query(
      `
    INSERT INTO catalog.exams (
      id,
      title,
      category,
      duration_seconds,
      attempt_limit,
      opens_at,
      closes_at
    )
    VALUES (
      $1,
      'Expiry regressions',
      'IT_CERTIFICATION',
      90,
      10,
      clock_timestamp() - interval '1 day',
      clock_timestamp() + interval '1 day'
    )
    `,
      [published.examId],
    );
    await publication.query(
      `
    INSERT INTO catalog.published_versions (
      id,
      exam_id,
      version,
      title,
      description,
      duration_seconds,
      attempt_limit,
      opens_at,
      closes_at,
      display_timezone,
      explanation_policy,
      category,
      published_by
    )
    VALUES (
      $1,
      $2,
      1,
      'Expiry regressions',
      '',
      90,
      10,
      clock_timestamp() - interval '1 day',
      clock_timestamp() + interval '1 day',
      'Asia/Ho_Chi_Minh',
      'NEVER',
      'IT_CERTIFICATION',
      $3
    )
    `,
      [published.versionId, published.examId, publisher],
    );
    const sectionId = randomUUID();
    const questionId = randomUUID();
    const correctOption = randomUUID();
    await publication.query(
      `
      INSERT INTO catalog.published_sections (version_id, id, title, position)
      VALUES ($1, $2, 'One', 1)
      `,
      [published.versionId, sectionId],
    );
    await publication.query(
      `
      INSERT INTO catalog.published_questions (
        version_id,
        id,
        section_id,
        source_question_id,
        source_revision,
        type,
        prompt,
        explanation,
        points,
        position
      )
      VALUES ($1, $2, $3, $4, 1, 'SINGLE_CHOICE', 'Question', 'Hidden', 5, 1)
      `,
      [published.versionId, questionId, sectionId, randomUUID()],
    );
    await publication.query(
      `
      INSERT INTO catalog.published_options (version_id, question_id, id, position, text)
      VALUES
        ($1, $2, $3, 1, 'A'),
        ($1, $2, $4, 2, 'B')
      `,
      [published.versionId, questionId, correctOption, randomUUID()],
    );
    await publication.query(
      `
      INSERT INTO catalog.published_answer_keys (version_id, question_id, option_id)
      VALUES ($1, $2, $3)
      `,
      [published.versionId, questionId, correctOption],
    );
    await publication.query(
      `
      UPDATE catalog.exams
      SET
        published = true,
        current_version_id = $2,
        revision = 2
      WHERE
        id = $1
      `,
      [published.examId, published.versionId],
    );
    await publication.query("COMMIT");
  } catch (error) {
    await publication.query("ROLLBACK");
    throw error;
  } finally {
    publication.release();
  }
  // Real upgrade from 0011 with invalid legacy provenance: the runner must
  // reject 0012 atomically, preserve history/constraint and never invent a kind.
  const invalid = await seedAttempt();
  await updateAccepted(workerDb, invalid, null);
  const historySql = `
    SELECT
      name,
      checksum
    FROM
      platform.schema_migrations
    ORDER BY
      name
  `;
  const historyBefore = (await fixture.query(historySql)).rows;
  await expect(migrate(config(loginUrl(owner), 1), migrations)).rejects.toThrow(
    "Migration failed: 0012_required_submission_kind.sql",
  );
  expect((await fixture.query(historySql)).rows).toEqual(historyBefore);
  expect(historyBefore).toHaveLength(11);
  const legacyConstraint = (
    await fixture.query(`
      SELECT
        pg_get_constraintdef(oid) AS definition
      FROM
        pg_constraint
      WHERE
        conrelid = 'assessment.attempts'::regclass
        AND conname = 'attempts_submission_kind_check'
    `)
  ).rows[0].definition;
  expect(legacyConstraint).not.toContain("submission_kind IS NOT NULL");
  const invalidRow = (
    await fixture.query(
      `
      SELECT
        submission_kind,
        submitted_at
      FROM
        assessment.attempts
      WHERE
        id = $1
    `,
      [invalid],
    )
  ).rows[0];
  expect(invalidRow.submission_kind).toBeNull();
  expect(invalidRow.submitted_at).toBeInstanceOf(Date);
  // Delete only synthetic corrupt data in this disposable DB; production repair
  // requires verified provenance and is deliberately not implemented here.
  await fixture.query(
    `
    DELETE FROM assessment.attempts
    WHERE
      id = $1
  `,
    [invalid],
  );
  expect(await migrate(config(loginUrl(owner), 1), migrations)).toEqual([
    "0012_required_submission_kind.sql",
    "0013_expiry_retry_schedule.sql",
    "0014_submission_dispatch.sql",
    "0015_grading_worker.sql",
    "0016_grading_recovery.sql",
    "0017_assessment_retention.sql",
    "0018_leaderboard_cursor_epochs.sql",
  ]);
  expect(await migrate(config(loginUrl(owner), 1), migrations)).toEqual([]);
  migrationUpgradeVerified = true;
}, 60_000);

beforeEach(async () => {
  await clearOutboxFailure();
  await fixture.query("TRUNCATE assessment.attempts, platform.outbox CASCADE");
});

afterAll(async () => {
  await Promise.all([runtimeDb?.close(), workerDb?.close(), secondWorkerDb?.close()]);
  await fixture?.end();
  try {
    let connections = -1;
    for (let poll = 0; poll < 100; poll += 1) {
      connections = Number(
        (
          await admin.query(
            `
        SELECT
          count(*)::integer AS connections
        FROM
          pg_stat_activity
        WHERE
          datname = $1
      `,
            [name],
          )
        ).rows[0].connections,
      );
      if (connections === 0) break;
      await new Promise((resolve) => setTimeout(resolve, 10));
    }
    expect(connections).toBe(0);
    expect(fixtureErrors).toEqual([]);
    await admin.query(`DROP DATABASE IF EXISTS ${name}`);
    await admin.query(`DROP ROLE IF EXISTS ${owner}, ${runtimeLogin}, ${workerLogin}`);
  } finally {
    await admin.end();
  }
});

describe("ATT-07 independent expiry regressions", () => {
  it("fails a corrupt 0011 upgrade atomically, then applies 0012/0013 and reruns unchanged", () => {
    expect(migrationUpgradeVerified).toBe(true);
  });
  it.each(["runtime", "expiry"] as const)(
    "rejects an accepted NULL provenance UPDATE with the %s login",
    async (login) => {
      const id = await seedAttempt();
      await expect(
        updateAccepted(login === "runtime" ? runtimeDb : workerDb, id, null),
      ).rejects.toMatchObject({ code: "23514" });
      expect(await state(id)).toMatchObject({
        status: "IN_PROGRESS",
        revision: 1,
        submission_kind: null,
        submission_id: null,
        events: 0,
      });
    },
  );

  it("rejects an accepted NULL provenance INSERT with the runtime login", async () => {
    const id = randomUUID();
    const userId = await insertUser();
    await expect(
      runtimeDb.query(
        "assessment.write",
        `
        INSERT INTO assessment.attempts (
          id,
          user_id,
          exam_id,
          version_id,
          status,
          started_at,
          deadline,
          submitted_at,
          submission_id,
          submission_event_id,
          expired,
          revision,
          submission_kind
        )
        VALUES (
          $1,
          $2,
          $3,
          $4,
          'EXPIRED',
          clock_timestamp() - interval '2 hours',
          clock_timestamp() - interval '1 hour',
          clock_timestamp(),
          gen_random_uuid(),
          gen_random_uuid(),
          true,
          2,
          NULL
        )
        `,
        [id, userId, published.examId, published.versionId],
      ),
    ).rejects.toMatchObject({ code: "23514" });
    expect(
      (
        await fixture.query(
          `
        SELECT
          id
        FROM
          assessment.attempts
        WHERE
          id = $1
        `,
          [id],
        )
      ).rows,
    ).toEqual([]);
  });

  it.each([
    { kind: "MANUAL", offset: 3600, status: "SUBMITTED" },
    { kind: "MANUAL", offset: -60, status: "EXPIRED" },
    { kind: "DEADLINE", offset: -60, status: "EXPIRED" },
  ] as const)(
    "keeps valid $kind/$status provenance immutable",
    async ({ kind, offset, status }) => {
      const id = await seedAttempt(offset);
      await updateAccepted(kind === "MANUAL" ? runtimeDb : workerDb, id, kind);
      const accepted = await state(id);
      expect(accepted).toMatchObject({ status, revision: 2, submission_kind: kind });
      for (const changed of [null, kind === "MANUAL" ? "DEADLINE" : "MANUAL"]) {
        await expect(
          runtimeDb.query(
            "assessment.write",
            `
            UPDATE assessment.attempts
            SET
              submission_kind = $2
            WHERE
              id = $1
            `,
            [id, changed],
          ),
        ).rejects.toMatchObject({ code: "23514" });
      }
      expect(await state(id)).toEqual(accepted);
    },
  );

  it.each([1, 2])(
    "advances a healthy row behind a full poison batch of %i without marking failures terminal",
    async (batch) => {
      const poison = [];
      for (let n = 0; n < batch; n += 1) poison.push(await seedAttempt(-120 - batch + n));
      const healthy = await seedAttempt(-60);
      await rejectOutboxFor(poison);
      try {
        const worker = sweep(workerDb, batch);
        for (let tick = 0; tick < 6; tick += 1) await worker.runOnce(randomUUID());
        expect(await state(healthy)).toMatchObject({
          status: "EXPIRED",
          revision: 2,
          submission_kind: "DEADLINE",
          events: 1,
        });
        for (const id of poison) {
          expect(await state(id)).toMatchObject({
            status: "IN_PROGRESS",
            revision: 1,
            submission_kind: null,
            submission_id: null,
            events: 0,
          });
        }
      } finally {
        await clearOutboxFailure();
      }
    },
  );

  it("recovers rolled-back rows after restart and commits once when two workers retry", async () => {
    const ids = [await seedAttempt(-120), await seedAttempt(-60)];
    await rejectOutboxFor(ids);
    try {
      const failed = await sweep(workerDb, 2).runOnce(randomUUID());
      expect(failed.failed).toBe(2);
      for (const id of ids) {
        expect(await state(id)).toMatchObject({
          status: "IN_PROGRESS",
          revision: 1,
          events: 0,
          expiry_retry_count: 1,
          expiry_retry_after: expect.any(Date),
        });
      }
    } finally {
      await clearOutboxFailure();
    }
    // New use-case instances simulate recomposition; the existing ATT-07 suite
    // separately starts/stops the compiled process. PostgreSQL remains real.
    // Extend the persisted eligibility only in this isolated fixture so a busy
    // CI host cannot accidentally cross the one-second initial retry window.
    await fixture.query(
      `
      UPDATE assessment.attempts
      SET
        expiry_retry_after = clock_timestamp() + interval '10 minutes'
      WHERE
        id = ANY ($1::uuid[])
      `,
      [ids],
    );
    const cooling = await Promise.all(ids.map(state));
    const beforeEligibility = await Promise.all([
      sweep(workerDb, 10).runOnce(randomUUID()),
      sweep(secondWorkerDb, 10).runOnce(randomUUID()),
    ]);
    for (const result of beforeEligibility) {
      expect(result).toMatchObject({ processed: 0, failed: 0 });
    }
    expect(await Promise.all(ids.map(state))).toEqual(cooling);
    await fixture.query(
      `
      UPDATE assessment.attempts
      SET
        expiry_retry_after = clock_timestamp() - interval '1 second'
      WHERE
        id = ANY ($1::uuid[])
      `,
      [ids],
    );
    await Promise.all([
      sweep(workerDb, 10).runOnce(randomUUID()),
      sweep(secondWorkerDb, 10).runOnce(randomUUID()),
    ]);
    const committed = await Promise.all(ids.map(state));
    await Promise.all([
      sweep(workerDb, 10).runOnce(randomUUID()),
      sweep(secondWorkerDb, 10).runOnce(randomUUID()),
    ]);
    expect(await Promise.all(ids.map(state))).toEqual(committed);
    for (const row of committed) {
      expect(row).toMatchObject({
        status: "EXPIRED",
        revision: 2,
        submission_kind: "DEADLINE",
        submission_id: expect.any(String),
        submission_event_id: expect.any(String),
        events: 1,
      });
    }
  });

  it.each(["expiry_retry_count", "expiry_retry_after"] as const)(
    "rejects runtime changes to scheduler-only %s metadata",
    async (column) => {
      const id = await seedAttempt();
      // Only the two fixture-owned identifiers above are interpolated.
      await expect(
        runtimeDb.query(
          "assessment.write",
          `
          UPDATE assessment.attempts
          SET
            ${column} = ${column}
          WHERE
            id = $1
          `,
          [id],
        ),
      ).rejects.toMatchObject({ code: "42501" });
      expect(await state(id)).toMatchObject({ expiry_retry_count: 0, expiry_retry_after: null });
    },
  );

  it("does not defer or mutate an attempt after another submit has won", async () => {
    const id = await seedAttempt();
    await updateAccepted(runtimeDb, id, "MANUAL");
    const accepted = await state(id);
    await workerDb.transaction(() => new PostgresAttemptRepository(workerDb).deferExpiry(id));
    expect(await state(id)).toEqual(accepted);
  });

  it.each([
    { count: 0, next: 1, minMs: 800, maxMs: 1200 },
    { count: 4, next: 5, minMs: 12800, maxMs: 19200 },
    { count: 16, next: 16, minMs: 30000, maxMs: 30000 },
  ])(
    "persists DB-clock retry bounds and capped count after $count prior failures",
    async ({ count, next, minMs, maxMs }) => {
      const id = await seedAttempt();
      await fixture.query(
        `
        UPDATE assessment.attempts
        SET
          expiry_retry_count = $2
        WHERE
          id = $1
        `,
        [id, count],
      );
      const before = (
        await fixture.query<{ now: Date }>("SELECT clock_timestamp() AS now")
      ).rows[0]!.now.getTime();
      await workerDb.transaction(() => new PostgresAttemptRepository(workerDb).deferExpiry(id));
      const after = (
        await fixture.query<{ now: Date }>("SELECT clock_timestamp() AS now")
      ).rows[0]!.now.getTime();
      const row = await state(id);
      expect(row).toMatchObject({
        status: "IN_PROGRESS",
        revision: 1,
        events: 0,
        submission_id: null,
        expiry_retry_count: next,
      });
      // PostgreSQL timestamptz(3) and the pg Date parser each round to milliseconds.
      expect(row.expiry_retry_after!.getTime()).toBeGreaterThanOrEqual(before + minMs - 2);
      expect(row.expiry_retry_after!.getTime()).toBeLessThanOrEqual(after + maxMs + 2);
    },
  );

  it("includes delayed outbox persistence in calibrated COMMIT ACK lag beyond a pre-commit witness", async () => {
    const { calibrateClock, createExpiryLagRecorder } = await import(
      pathToFileURL(resolve("scripts/expiry-lag.mjs")).href
    );
    const id = await seedAttempt();
    await fixture.query(`
      CREATE TABLE public.expiry_fix_commit_witness (
        attempt_id uuid PRIMARY KEY,
        observed_at timestamptz NOT NULL
      )
    `);
    await fixture.query(`
      CREATE FUNCTION public.expiry_fix_delay() RETURNS trigger
      LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $fn$
      BEGIN
        PERFORM pg_sleep(0.2);
        INSERT INTO public.expiry_fix_commit_witness (attempt_id, observed_at)
        VALUES (NEW.aggregate_id, clock_timestamp());
        RETURN NEW;
      END
      $fn$
    `);
    await fixture.query(`
      CREATE TRIGGER expiry_fix_delay
        AFTER INSERT ON platform.outbox
        FOR EACH ROW EXECUTE FUNCTION public.expiry_fix_delay()
    `);
    const calibration = await calibrateClock(
      async () =>
        (
          await fixture.query(`
        SELECT
          to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS now
      `)
        ).rows[0].now,
    );
    const recorder = createExpiryLagRecorder({ calibration });
    const observedSweep = new DeadlineSweep(
      new PostgresAttemptRepository(workerDb),
      new PostgresSubmissionOutbox(workerDb),
      workerDb,
      1,
      recorder,
    );
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 1, failed: 0 });
    const witness = (
      await fixture.query<{ lower_lag_ms: number }>(
        `
      SELECT
        (extract(epoch FROM (w.observed_at - a.deadline)) * 1000)::float8 AS lower_lag_ms
      FROM
        public.expiry_fix_commit_witness w
        JOIN assessment.attempts a ON a.id = w.attempt_id
      WHERE
        a.id = $1
    `,
        [id],
      )
    ).rows[0]!;
    const sample = recorder.summary();
    expect(sample.deadlineToCommitAckObservedLagMs.sampleCount).toBe(1);
    expect(sample.deadlineToAcceptanceLagMs.sampleCount).toBe(1);
    expect(
      sample.deadlineToCommitAckObservedLagMs.p50Ms + calibration.uncertaintyMs + 2,
    ).toBeGreaterThanOrEqual(witness.lower_lag_ms);
    expect(
      sample.deadlineToCommitAckObservedLagMs.p50Ms -
        sample.deadlineToAcceptanceLagMs.p50Ms +
        calibration.uncertaintyMs +
        2,
    ).toBeGreaterThanOrEqual(190);
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 0 });
    expect(recorder.summary().deadlineToCommitAckObservedLagMs.sampleCount).toBe(1);
  });

  it("does not observe a rolled-back acceptance and observes exactly once after durable retry", async () => {
    const id = await seedAttempt();
    await rejectOutboxFor([id]);
    let observations = 0;
    const observedSweep = new DeadlineSweep(
      new PostgresAttemptRepository(workerDb),
      new PostgresSubmissionOutbox(workerDb),
      workerDb,
      1,
      {
        committed: () => {
          observations += 1;
        },
      },
    );
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 0, failed: 1 });
    expect(observations).toBe(0);
    expect(await state(id)).toMatchObject({ status: "IN_PROGRESS", revision: 1, events: 0 });
    await clearOutboxFailure();
    await fixture.query(
      `
      UPDATE assessment.attempts
      SET
        expiry_retry_after = clock_timestamp() - interval '1 second'
      WHERE
        id = $1
    `,
      [id],
    );
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 1, failed: 0 });
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 0, failed: 0 });
    expect(observations).toBe(1);
    expect(await state(id)).toMatchObject({ status: "EXPIRED", revision: 2, events: 1 });
  });

  it("cannot retry a committed acceptance when its observation collector throws", async () => {
    const id = await seedAttempt();
    let observations = 0;
    const observedSweep = new DeadlineSweep(
      new PostgresAttemptRepository(workerDb),
      new PostgresSubmissionOutbox(workerDb),
      workerDb,
      1,
      {
        committed: () => {
          observations += 1;
          throw new Error("collector unavailable");
        },
      },
    );
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 1, failed: 0 });
    expect(await observedSweep.runOnce(randomUUID())).toMatchObject({ processed: 0, failed: 0 });
    expect(observations).toBe(1);
    expect(await state(id)).toMatchObject({
      status: "EXPIRED",
      revision: 2,
      events: 1,
      expiry_retry_count: 0,
      expiry_retry_after: null,
    });
  });

  it("reads authoritative time after an observed row-lock wait crosses the deadline", async () => {
    const id = await seedAttempt(3600);
    const userId = (await state(id)).user_id;
    const held = await fixture.connect();
    await held.query("BEGIN");
    await held.query(
      `
      SELECT
        id
      FROM
        assessment.attempts
      WHERE
        id = $1
      FOR UPDATE
      `,
      [id],
    );
    const waiting = runtimeDb.transaction(() =>
      new PostgresAttemptRepository(runtimeDb).lockOwned(id, userId),
    );
    let observed = false;
    try {
      for (let poll = 0; poll < 40; poll += 1) {
        const row = (
          await admin.query<{ waiting: number }>(
            `
            SELECT
              count(*)::integer AS waiting
            FROM
              pg_stat_activity
            WHERE
              datname = $1
              AND wait_event_type = 'Lock'
            `,
            [name],
          )
        ).rows[0];
        if (row?.waiting) {
          observed = true;
          break;
        }
        await new Promise((resolve) => setTimeout(resolve, 5));
      }
      await held.query(
        `
        UPDATE assessment.attempts
        SET
          deadline = clock_timestamp()
        WHERE
          id = $1
        `,
        [id],
      );
      await held.query("COMMIT");
      const locked = await waiting;
      expect(observed).toBe(true);
      expect(locked).not.toBeNull();
      expect(Date.parse(locked!.serverNow)).toBeGreaterThanOrEqual(Date.parse(locked!.deadline));
    } finally {
      await held.query("ROLLBACK").catch(() => undefined);
      held.release();
      await waiting.catch(() => undefined);
    }
  });

  it("uses a natural deadline index range for an empty claim among 100000 future attempts", async () => {
    await fixture.query(
      `
      WITH people AS (
        INSERT INTO identity.users (id, email, password_hash, display_name)
        SELECT
          gen_random_uuid(),
          replace(gen_random_uuid()::text, '-', '') || '@example.test',
          'fixture-not-a-real-password-hash',
          'Future attempt'
        FROM
          generate_series(1, 100000)
        RETURNING
          id
      )
      INSERT INTO assessment.attempts (
        id,
        user_id,
        exam_id,
        version_id,
        status,
        started_at,
        deadline,
        revision
      )
      SELECT
        gen_random_uuid(),
        id,
        $1,
        $2,
        'IN_PROGRESS',
        clock_timestamp() - interval '2 hours',
        clock_timestamp() + interval '1 hour',
        1
      FROM
        people
      `,
      [published.examId, published.versionId],
    );
    await fixture.query("ANALYZE assessment.attempts");
    const client = await fixture.connect();
    try {
      await client.query("BEGIN");
      const result = await client.query<{ "QUERY PLAN": Array<{ Plan: PlanNode }> }>(
        `EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${claimDueSql}`,
        [[]],
      );
      const plan = result.rows[0]?.["QUERY PLAN"][0]?.Plan;
      if (!plan) throw new Error("Missing PostgreSQL plan");
      const attempts = flattenPlan(plan).filter((node) => node["Relation Name"] === "attempts");
      expect(attempts.some((node) => (node["Index Cond"] ?? "").includes("deadline"))).toBe(true);
      expect(attempts.reduce((sum, node) => sum + (node["Rows Removed by Filter"] ?? 0), 0)).toBe(
        0,
      );
      await client.query("ROLLBACK");
      expect(await sweep(workerDb, 1).runOnce(randomUUID())).toMatchObject({
        processed: 0,
        failed: 0,
        due: 0,
      });
    } finally {
      await client.query("ROLLBACK").catch(() => undefined);
      client.release();
    }
  }, 60_000);
});

interface PlanNode {
  "Relation Name"?: string;
  "Index Cond"?: string;
  "Rows Removed by Filter"?: number;
  Plans?: PlanNode[];
}

function flattenPlan(plan: PlanNode): PlanNode[] {
  return [plan, ...(plan.Plans ?? []).flatMap(flattenPlan)];
}
