include classpath("application.conf")
node-address { protocol = http, host = "*", port = 9324, context-path = "" }
rest-sqs { enabled = true, bind-port = 9324, bind-hostname = "0.0.0.0" }
queues {
  scoring { defaultVisibilityTimeout = 90 seconds, receiveMessageWait = 10 seconds, deadLettersQueue { name = "scoring-dlq", maxReceiveCount = 5 } }
  scoring-dlq {}
}
